### ISSUE TITLE
Add Support for armeabi-v7a and x86

### ISSUE THREAD

**Issue by Hannes1** [pengzhendong/wenet-openfst-android#1]
Hi, thanks for the great work on wenet I was playing around with the android demo and react native and was wondering if you could add the libs for armeabi-v7a and x86 or maybe give me some instructions.

I have compiled openfst using vosks build-vosk script for these architectures before but I'm not skilled enough to figure out what's needed for wenet.

**Comment by pengzhendong** [comment]
Supported.
